"""empty message

Revision ID: 902d977a2a01
Revises: 76ca334154ca
Create Date: 2018-08-27 20:12:28.468199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '902d977a2a01'
down_revision = '76ca334154ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ideas', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ideas', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ideas', type_='foreignkey')
    op.drop_column('ideas', 'user_id')
    # ### end Alembic commands ###
